# Generated by Django 5.0.4 on 2024-05-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=50, verbose_name='body'),
        ),
    ]
