# Generated by Django 5.0.4 on 2024-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image_post_likes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
